# Generated by Django 4.2.7 on 2023-11-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0001_initial"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.FloatField()),
                ("respiratory_rate", models.IntegerField()),
                ("heart_rate", models.IntegerField()),
                ("blood_pressure", models.CharField(max_length=100)),
                ("oxygen_saturation", models.IntegerField()),
                ("pain_scale", models.IntegerField()),
                ("random_blood_sugar", models.FloatField()),
                ("remarks", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="patient.person"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transaction",
                    ),
                ),
            ],
        ),
    ]
